### ISSUE TITLE
RhinoSurface.from_guid doesn't work

### ISSUE THREAD

**Issue by baolianliu** [compas-dev/compas#1039]
**Describe the bug**
Hi, I created a rhinosurface in Rhino7, then use code "surface_guid =  compas_rhino.select_surface("Select a surface.")" to select this surface in grasshopper. From this step, I got a "guid" type of the surface. Then I tried to convert this "guid" surface into Rhinosurface, BUT it doesn't work with error "NullReferenceException". Can anybody help me where is the problem?

**Expected behavior**
A RhinoGeometry object from guid.

**Screenshots**
![image](https://user-images.githubusercontent.com/91332357/165795117-28af363a-eb1e-451f-aece-24bd376b510c.png)
![image](https://user-images.githubusercontent.com/91332357/165795950-910aae4e-64e3-422c-aeb1-fc7fe481b199.png)
![image](https://user-images.githubusercontent.com/91332357/165796052-c05485ce-761e-4831-9dc1-b9408637a5ff.png)

**Desktop (please complete the following information):**
-  Windows 10
 - Python version 3.9.6
 - Python package manager : conda
 - COMPAS version: 1.15.1

**Comment by gonzalocasas** [comment]
If you do this from Grasshopper, instead of using the `select_surface` method (that works on Rhino side, not GH), and `from_guid`, use a referenced geometry input + `from_geometry`:

![image](https://user-images.githubusercontent.com/933277/169839812-8711192d-1ceb-4578-8dd8-f81f1d2d30f9.png)


Notice that I selected `GeometryBase` as type hint for the `surface` input.

I'm going to go ahead and close this, but feel free to keep commenting, or re-open it if this doesn't solve your problem!
