### ISSUE TITLE
Move `brep` pakcage out of `geometry`

### ISSUE THREAD

**Issue by chenkasirer** [compas-dev/compas#1195]

**Comment by jf---** [comment]
@tomvanmele -1 since surfaces and curves are there too. 🧐 a BRep is a topological layer on top of a surface, so strictly speaking brep could move to `compas.topology` but since the subpackages are broadly defines (`shapes`), I'd say hit close

<img width="146" alt="image" src="https://github.com/compas-dev/compas/assets/620988/9d3a486f-adcf-4231-8a11-262703a12a3a">

**Comment by tomvanmele** [comment]
breps were originally in `compas.brep` because that is where they are in `compas_occ`, and there this is the case because that is where they are in `OCC`, but after going back and forth a few times, we decided to leave them in geometry (at least for the time being)
