### ISSUE TITLE
Problem with Mesh.face_circle()

### ISSUE THREAD

**Issue by robin-oval** [compas-dev/compas#1389]
The `Frame` in `Circle` in `Mesh.face_circle()` is wrongly initiated as `Circle((point, normal), radius)`, instead of `Circle(radius, (point_0, point_1, point_2))`.

**Comment by robin-oval** [comment]
I saw them, but it seems that `Mesh.face_circle()` uses the base
constructor, not `from_plane_and_radius`.

**Comment by petrasvestartas** [comment]
I also get the same error:

```python

from compas.geometry import Box
from compas_viewer import Viewer
from compas.datastructures import Mesh

# Create a box.
box = Box(1, 1, 1)
mesh = Mesh.from_shape(box)
faces = list(mesh.faces())

# Vizualize geometry.
viewer = Viewer()
viewer.scene.add(mesh)
viewer.scene.add(mesh.face_circle(faces[1]))
viewer.show()
```


The circle constructor needs to be changed to this:

```python
    def face_circle(self, face):
        """The circle of a face.

        Parameters
        ----------
        face : int
            The face identifier. 

        Returns
        -------
        :class:`compas.geometry.Circle`
            The circle of the face.

        """
        from compas.geometry import bestfit_circle_numpy
        point, normal, radius = bestfit_circle_numpy(self.face_coordinates(face))
        return Circle.from_plane_and_radius(Plane(point, normal), radius)
```

Instead of using the default constructor
```Python
Circle((point, normal), radius)
```

![image](https://github.com/user-attachments/assets/fa414a91-57c5-417a-8838-2afd7315a67f)

@robin-oval  can you make a pull-request?

And it would be great to make unit-tests for such methods in compas. I am wondering if it makes sense to make more unit-tests for other methods in compas ?

**Comment by robin-oval** [comment]
Solved with PR
