### ISSUE TITLE
cloning the repository won't work (wrong URL)

### ISSUE THREAD

**Issue by franaudo** [compas-dev/compas#193]
the URL shown when pushing on the  _clone or download_ button is 

> https://github.com/compas-dev/compas.git

instead of

> https://github.com/compas-dev/compas

Using the second one, it will correctly clone the repository

**Comment by gonzalocasas** [comment]
@nefelogeta not sure if I understand what you mean. The URL shown on the green "Clone or download" button is handled entirely by github, and it is the correct URL for cloning the repository. The latter one also works, but is less correct than the first.

**Comment by franaudo** [comment]
@gonzalocasas the first one doesn't work when I try to clone it using github desktop, but if I change it, it works just fine. Maybe it is related to a configuration of my GitHub Desktop. I will try on another computer.

**Comment by gonzalocasas** [comment]
I tested this with Github Desktop and the command line client and it works just fine. Which version of Github Desktop are you running? Could it be outdated or somehow buggy?

I'm going to close this because I'm certain it's not a problem with the `compas` repository, but feel free to keep commenting on it.

**Comment by franaudo** [comment]
Thanks. I still have the problem but it needs to be a configuration of my GitHub Desktop. The workaround I suggested is still valid, but if I understand why I will post it here.

Thanks again for your help!
