### ISSUE TITLE
start stop rpc

### ISSUE THREAD

**Issue by tomvanmele** [compas-dev/compas#223]
@gonzalocasas 

i have updated the example to reflect how RPC would typically be most useful: start.py + run.py + stop.py

the way i wrote the individual scripts will work but it is a bit of a hack. should we formalise the use of RPC not in that way?

thanks,
tom

**Comment by gonzalocasas** [comment]
I don't really think there's a need for starting the proxy explicitly with a separate script. In fact, that's actually the beauty of it, not having to care about the proxy server part. And regarding stopping it, since this is a pretty light process, I would go as far as to say that it's not even needed to stop it. People that care about that will use the `with` statement, or stop it explicitly, and for everyone else, if they use the proxy, they will have the process running, and it will be there as long as they have their CAD open, which is not too bad either.
