### ISSUE TITLE
Wrong closest_point_in_cloud documentation

### ISSUE THREAD

**Issue by Achillx** [compas-dev/compas#286]
**Describe the bug**
The documentation says that it returns the distance to the closest point, but instead it returns the squared distance!
`closest_point_in_cloud` uses `sort_points` which uses `distance_point_point_sqrd`

**Expected behavior**
Write that it returns the squared distance, or return `closest_point_in_cloud` to return `sqrt(data[0])`.

**Comment by yck011522** [comment]
Yes, I agree it is probably fine for the sorting function to use squared distance to sort. But if these distances are to be returned, it is better to properly document. Otherwise everyone expects a clostestpoint function to return normal distance.

I'm not sure if other function that uses `distance_point_point_sqrd` are also incorrectly documented.

**Comment by tomvanmele** [comment]
thanks for the report.
will fix in next release...

**Comment by tomvanmele** [comment]
solved since 92cbf6f8
