### ISSUE TITLE
not all edges on boundary returned

### ISSUE THREAD

**Issue by worbit** [compas-dev/compas#318]
The method `mesh.edges_on_boundary` ([here](https://github.com/compas-dev/compas/blob/master/src/compas/datastructures/mesh/_mesh.py#L2933)) seems to not return *all* the keys of boundary edges, as also the visualisation example in the Tutorials section shows: https://compas-dev.github.io/main/tutorials/meshes.html#visualisation-1 as only the left and top edges are shown in green.

**Comment by tomvanmele** [comment]
this seems to be caused by the `oriented=True` default parameter. (not sure why and when it was added, can't remember it always being there).

if `oriented` is set to `False`, the example works as expected, but in both cases all edges are returned. however, when `oriented` is set to `True`, not all returned edges are actually edges of the mesh if the orientation is taken is into account. therefore, the drawing function doesn't work as expected.

perhaps the function should be split into two, with one returning actual edges (`orientation=False`) and the other returning oriented half-edges (`orientation=True`).

in any case, the default value of the parameter should not be `True`, as it produced unexpected results...

will propose a fix!
