### ISSUE TITLE
Key error with Mesh.boundary()

### ISSUE THREAD

**Issue by Licini** [compas-dev/compas#325]
**To Reproduce**

```
import compas
import json
from compas.datastructures import Mesh
mesh = Mesh.from_obj(compas.get('faces.obj'))
mesh.boundaries()
```

**Expected behavior**

```
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import compas
>>> import json
>>> from compas.datastructures import Mesh
>>> mesh = Mesh.from_obj(compas.get('faces.obj'))
>>> mesh.boundaries()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lichen7/WORK/compas/src/compas/datastructures/mesh/_mesh.py", line 2104, in boundaries
    boundary.append(boundary_edges[boundary[-1]])
KeyError: 35
>>> 
```

**Desktop (please complete the following information):**
 - OS: OS X
 - Python version 3.7
 - Python package manager conda

**Comment by tomvanmele** [comment]
this is caused by a recent change in the function `edges_on_boundary`.
the code in the `boundaries` function should be `boundary_edges = {u: v for u, v in self.edges_on_boundary(True)}`.

in any case, the function `edges_on_boundary` is confusing and should perhaps be split up into two different functions with more explicit names...
