### ISSUE TITLE
API reference issues -

### ISSUE THREAD

**Issue by mattiskoh** [compas-dev/compas#794]
**Describe the bug**
More than once I have encountered that certain COMPAS functions are not shown in the API Reference, although they have already been implemented and can be found in the source code. This is slightly annoying :( . 

e.g. for `intersection_polyline_plane`
![image](https://user-images.githubusercontent.com/17108767/112180136-918e3400-8bfb-11eb-99cb-20b261e21cbd.png)
![image](https://user-images.githubusercontent.com/17108767/112180178-9b179c00-8bfb-11eb-9315-0518547dcaa2.png)
![image](https://user-images.githubusercontent.com/17108767/112180279-b4204d00-8bfb-11eb-8b21-20496595dd6f.png)
clearly it is implemented @ line 318 ->  compas/geometry/intersections/intersections.py

will add additional functions as I encounter them.. 

On the other hand, functions that have not been implemented can be found in the API search...  e.g. `trimesh_slice`

**Comment by tomvanmele** [comment]
it is indeed possible that the API documentation is not always entirely up to date. will try to fix...

as for the slice function. it is a pluggable, meaning that the implementation is defined somewhere else (for example because it relies on functionality that is not part of `compas` core). in this case, one possible implementation is in `compas_cgal`. so if you have `compas_cgal` installed the function should work...

perhaps we need a better way to document this :)

**Comment by gonzalocasas** [comment]
would it be possible to add a unit test that cross-check the API docs against the API recorded in the json file (of the recently added unit test for api stability)? basically, if sphinx has an api to access the parsed TOC, we should at least ensure that all symbols are present in the TOC.

**Comment by mattiskoh** [comment]
just also found that `intersection_segment_polyline` is also not showing up

**Comment by gonzalocasas** [comment]
I think this is now much better, at least for the API stuff, search now includes all of them and we've been cleaning up and ensuring all functions are actually exposed, so, perhaps this can be closed, @mattiskoh ?
